wandb_version: 1

epochs:
  desc: null
  value: 1000
normalize interval:
  desc: null
  value:
  - -1
  - 1
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708503227.078953
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 16
      4: 3.9.18
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
